### PR TITLE
Add support for virtio-scsi via stemcell cloud properties

### PR DESCRIPTION
**Pull request by leosco**
References:

- https://wiki.openstack.org/wiki/Documentation/HypervisorTuningGuide#Symptoms_of_Being_Disk_Bound
- https://wiki.openstack.org/wiki/Documentation/HypervisorTuningGuide#Instance_and_Image_Configuration_4

### CODE REVIEW

**Comment by jpalermo** [comment]
Adding reviewers. Could you also sign the CLA?

**Comment by sainaveenkumargedala** [comment]
Hello @jpalermo,

Can you also add this property  hw_vif_multiqueue_enabled=true along with the properties that are available in this PR hw_disk_bus=scsi and hw_scsi_model=virtio-scsi

Thanks,
SaiNaveenKumarGedala

**Comment by leosco** [comment]
> Adding reviewers. Could you also sign the CLA?

Still waiting on approval for this, apologies for the delay

**Review by ystros — APPROVED** [review]

**Review by lnguyen — APPROVED** [review]

**Comment by leosco** [comment]
@rkoster all set

**Pull request merged**
